import {LOCATION_ATTRIBUTES} from '../api/CollectionLocationAPI'
import {STUDENT_ATTRIBUTES} from '../api/CollectionStudentAPI'
import {CLASS_FORM_ATTRIBUTES} from '../api/CollectionClassAPI'
import { FINANCE_ATTRIBUTES } from '../api/CollectionFinanceAPI'

export const testing_students = [
    {
    [STUDENT_ATTRIBUTES.CONTACT_NAME]:'Raymond',
    [STUDENT_ATTRIBUTES.CREATED_DATE]: 1642325816961,
    [STUDENT_ATTRIBUTES.EMAIL]:'Raymond11@gmail.com',
    [STUDENT_ATTRIBUTES.PHONE]:'69847363',
    [STUDENT_ATTRIBUTES.STATE]:'normal',

    [STUDENT_ATTRIBUTES.STUDENT_LIST]:[{
    [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 4,
    [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'1992',
    [STUDENT_ATTRIBUTES.GENDER]:'male',
    [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Raymond',
    [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1200'
    }]},

    {
    [STUDENT_ATTRIBUTES.CONTACT_NAME]:'Christopher',
    [STUDENT_ATTRIBUTES.CREATED_DATE]:1625865226000,
    [STUDENT_ATTRIBUTES.EMAIL]:'ultrices@icloud.ca',
    [STUDENT_ATTRIBUTES.PHONE]:'48602653',
    [STUDENT_ATTRIBUTES.STATE]:'normal',

    [STUDENT_ATTRIBUTES.STUDENT_LIST]:[{
    [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 1,
    [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'1998',
    [STUDENT_ATTRIBUTES.GENDER]:'female',
    [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Christopher',
    [STUDENT_ATTRIBUTES.TUITION_VALUE]:'400'
    }]},

    {
    [STUDENT_ATTRIBUTES.CONTACT_NAME]:'Farrah',
    [STUDENT_ATTRIBUTES.CREATED_DATE]:1669124896000,
    [STUDENT_ATTRIBUTES.EMAIL]:'ac@google.net',
    [STUDENT_ATTRIBUTES.PHONE]:'35795455',
    [STUDENT_ATTRIBUTES.STATE]:'normal',

    [STUDENT_ATTRIBUTES.STUDENT_LIST]:[{
    [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 1,
    [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'1904',
    [STUDENT_ATTRIBUTES.GENDER]:'none',
    [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Farrah',
    [STUDENT_ATTRIBUTES.TUITION_VALUE]:'400'
    }]},

    {
    [STUDENT_ATTRIBUTES.CONTACT_NAME]:'Simone',
    [STUDENT_ATTRIBUTES.CREATED_DATE]:1666118191000,
    [STUDENT_ATTRIBUTES.EMAIL]:'eget.massa@icloud.com',
    [STUDENT_ATTRIBUTES.PHONE]:'17712323',
    [STUDENT_ATTRIBUTES.STATE]:'normal',

    [STUDENT_ATTRIBUTES.STUDENT_LIST]:[{
    [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 4,
    [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'2012',
    [STUDENT_ATTRIBUTES.GENDER]:'male',
    [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Isaiah',
    [STUDENT_ATTRIBUTES.TUITION_VALUE]:'500'
    }]},

    {
    [STUDENT_ATTRIBUTES.CONTACT_NAME]:'Micah',
    [STUDENT_ATTRIBUTES.CREATED_DATE]:1613977205000,
    [STUDENT_ATTRIBUTES.EMAIL]:'tempus.eu@protonmail.edu',
    [STUDENT_ATTRIBUTES.PHONE]:'37629088',
    [STUDENT_ATTRIBUTES.STATE]:'normal',

    [STUDENT_ATTRIBUTES.STUDENT_LIST]:[{
    [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 4,
    [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'2017',
    [STUDENT_ATTRIBUTES.GENDER]:'female',
    [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Lara',
    [STUDENT_ATTRIBUTES.TUITION_VALUE]:'2400'
    },
    {[STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 4,
    [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'2015',
    [STUDENT_ATTRIBUTES.GENDER]:'male',
    [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Devin',
    [STUDENT_ATTRIBUTES.TUITION_VALUE]:'2400'}
    ]},

    {
    [STUDENT_ATTRIBUTES.CONTACT_NAME]:'Igor',
    [STUDENT_ATTRIBUTES.CREATED_DATE]:1652460295000,
    [STUDENT_ATTRIBUTES.EMAIL]:'molestie.tortor@hotmail.com',
    [STUDENT_ATTRIBUTES.PHONE]:'35474484',
    [STUDENT_ATTRIBUTES.STATE]:'normal',

    [STUDENT_ATTRIBUTES.STUDENT_LIST]:[{
    [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 4,
    [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'1992',
    [STUDENT_ATTRIBUTES.GENDER]:'male',
    [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Nehru',
    [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1600'
    },
    {[STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 1,
    [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'2006',
    [STUDENT_ATTRIBUTES.GENDER]:'female',
    [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Salvador',
    [STUDENT_ATTRIBUTES.TUITION_VALUE]:'400'
    },
    {
        [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 4,
        [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'2016',
        [STUDENT_ATTRIBUTES.GENDER]:'none',
        [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Sasha',
    [   STUDENT_ATTRIBUTES.TUITION_VALUE]:'1200'
    }
    ]},

    {
    [STUDENT_ATTRIBUTES.CONTACT_NAME]:'Tad',
    [STUDENT_ATTRIBUTES.CREATED_DATE]:1657286241000,
    [STUDENT_ATTRIBUTES.EMAIL]:'odio.aliquam.vulputate@aol.edu',
    [STUDENT_ATTRIBUTES.PHONE]:'27112982',
    [STUDENT_ATTRIBUTES.STATE]:'normal',

    [STUDENT_ATTRIBUTES.STUDENT_LIST]:[{
    [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 4,
    [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'1988',
    [STUDENT_ATTRIBUTES.GENDER]:'none',
    [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Tad',
    [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1200'
    }]},

    {
    [STUDENT_ATTRIBUTES.CONTACT_NAME]:'Noelle',
    [STUDENT_ATTRIBUTES.CREATED_DATE]:1656435712000,
    [STUDENT_ATTRIBUTES.EMAIL]:'lectus@outlook.com',
    [STUDENT_ATTRIBUTES.PHONE]:'65781464',
    [STUDENT_ATTRIBUTES.STATE]:'normal',

    [STUDENT_ATTRIBUTES.STUDENT_LIST]:[{
    [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 4,
    [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'1968',
    [STUDENT_ATTRIBUTES.GENDER]:'none',
    [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Noelle',
    [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1200'
    }]},

    {
    [STUDENT_ATTRIBUTES.CONTACT_NAME]:'Wada',
    [STUDENT_ATTRIBUTES.CREATED_DATE]:1633916958000,
    [STUDENT_ATTRIBUTES.EMAIL]:'consectetuer.adipiscing@aol.edu',
    [STUDENT_ATTRIBUTES.PHONE]:'53689738',
    [STUDENT_ATTRIBUTES.STATE]:'normal',

    [STUDENT_ATTRIBUTES.STUDENT_LIST]:[{
    [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 4,
    [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'1986',
    [STUDENT_ATTRIBUTES.GENDER]:'male',
    [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Wade',
    [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1600'
    }]},

    {
    [STUDENT_ATTRIBUTES.CONTACT_NAME]:'Cyrus',
    [STUDENT_ATTRIBUTES.CREATED_DATE]:1655084793000,
    [STUDENT_ATTRIBUTES.EMAIL]:'in.faucibus.orci@hotmail.edu',
    [STUDENT_ATTRIBUTES.PHONE]:'11254228',
    [STUDENT_ATTRIBUTES.STATE]:'normal',

    [STUDENT_ATTRIBUTES.STUDENT_LIST]:[{
    [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 4,
    [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'1967',
    [STUDENT_ATTRIBUTES.GENDER]:'male',
    [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Dieter',
    [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1600'
    },{
    [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]: 4,
    [STUDENT_ATTRIBUTES.BIRTH_YEAR]:'1989',
    [STUDENT_ATTRIBUTES.GENDER]:'female',
    [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Dora',
    [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1600'
    }
    ]}
]

export const testing_classes = [
  {
  [CLASS_FORM_ATTRIBUTES.DURATION_MIN]:60,
  [CLASS_FORM_ATTRIBUTES.FREQUENCY]:'weekly',
  [CLASS_FORM_ATTRIBUTES.CLASS_NAME]:'Christopher',
  [CLASS_FORM_ATTRIBUTES.CREATED_DATE_TIME]:1615623569000,

  [CLASS_FORM_ATTRIBUTES.SELECTED_STUDENT]:[
  {Label: 0, value:[
        {
        [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]:4,
        //[key],
        [CLASS_FORM_ATTRIBUTES.STUDENT_STATE]:'normal',
        [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Christopher',
        [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1600'
          }
        ]
    }
    ],[CLASS_FORM_ATTRIBUTES.START_DATE_TIME]:'27/03/2021',
    [CLASS_FORM_ATTRIBUTES.STATE]:'normal'
  },

  {
  [CLASS_FORM_ATTRIBUTES.DURATION_MIN]:90,
  [CLASS_FORM_ATTRIBUTES.FREQUENCY]:'daily',
  [CLASS_FORM_ATTRIBUTES.CLASS_NAME]:'Lara, Isaiah',
  [CLASS_FORM_ATTRIBUTES.CREATED_DATE_TIME]:1619160157000,

  [CLASS_FORM_ATTRIBUTES.SELECTED_STUDENT]:[
  {Label: 0,
    value:[
      {
        [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]:4,
        //[key],
        [CLASS_FORM_ATTRIBUTES.STUDENT_STATE]:'normal',
        [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Lara',
        [STUDENT_ATTRIBUTES.TUITION_VALUE]:'2400'
      }
    ]
  },
  {Label: 1,
    value:[
      {
        [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]:4,
        //[key],
        [CLASS_FORM_ATTRIBUTES.STUDENT_STATE]:'normal',
        [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Isaiah',
        [STUDENT_ATTRIBUTES.TUITION_VALUE]:'2400'
      }
    ]
  }
],
  [CLASS_FORM_ATTRIBUTES.START_DATE_TIME]:'30/04/2021',
  [CLASS_FORM_ATTRIBUTES.STATE]:'voided'
  },

  {
  [CLASS_FORM_ATTRIBUTES.DURATION_MIN]:120,
  [CLASS_FORM_ATTRIBUTES.FREQUENCY]:'monthly',
  [CLASS_FORM_ATTRIBUTES.CLASS_NAME]:'Nehru, Salvador, Sasha',
  [CLASS_FORM_ATTRIBUTES.CREATED_DATE_TIME]:1624665576000,

  [CLASS_FORM_ATTRIBUTES.SELECTED_STUDENT]:[
  {Label: 0,
    value:[
      {
        [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]:4,
         //[key],
        [CLASS_FORM_ATTRIBUTES.STUDENT_STATE]:'normal',
        [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Nehrua',
        [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1600'
      }
    ]
  },
  {Label: 1,
    value:[
      {
        [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]:1,
        //[key],
        [CLASS_FORM_ATTRIBUTES.STUDENT_STATE]:'normal',
        [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Salvador',
        [STUDENT_ATTRIBUTES.TUITION_VALUE]:'400'
      }
    ]
  },
  {Label: 2,
    value:[
        {
        [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]:4,
         //[key],
        [CLASS_FORM_ATTRIBUTES.STUDENT_STATE]:'normal',
        [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Sasha',
        [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1200'
          }
        ]
      }
    ],
  [CLASS_FORM_ATTRIBUTES.START_DATE_TIME]:'03/07/2021',
  [CLASS_FORM_ATTRIBUTES.STATE]:'normal'
},

  {
  [CLASS_FORM_ATTRIBUTES.DURATION_MIN]:180,
  [CLASS_FORM_ATTRIBUTES.FREQUENCY]:'weekly',
  [CLASS_FORM_ATTRIBUTES.CLASS_NAME]:'Tad, Noelle, Wada, Dieter',
  [CLASS_FORM_ATTRIBUTES.CREATED_DATE_TIME]:1642252318000,

  [CLASS_FORM_ATTRIBUTES.SELECTED_STUDENT]:[{
  Label: 0,
    value:[
      {
        [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]:4,
         //[key],
        [CLASS_FORM_ATTRIBUTES.STUDENT_STATE]:'normal',
        [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Tad',
        [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1200'
      }
    ]
  },
  {Label: 1,
    value:[
      {
        [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]:1,
         //[key],
        [CLASS_FORM_ATTRIBUTES.STUDENT_STATE]:'quit',
        [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Noelle',
        [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1200'
      }
    ]
  },
  {Label: 2,
    value:[
      {
        [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]:4,
         //[key],
        [CLASS_FORM_ATTRIBUTES.STUDENT_STATE]:'normal',
        [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Wada',
        [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1600'
      }
    ]
  },
  {Label: 3,
    value:[
      {
        [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]:4,
         //[key],
        [CLASS_FORM_ATTRIBUTES.STUDENT_STATE]:'normal',
        [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Cyrus',
        [STUDENT_ATTRIBUTES.TUITION_VALUE]:'1600'
        }
      ]
    }
  ],
  [CLASS_FORM_ATTRIBUTES.START_DATE_TIME]:'20/01/2022',
  [CLASS_FORM_ATTRIBUTES.STATE]:'normal'

},

  {
  [CLASS_FORM_ATTRIBUTES.DURATION_MIN]:120,
  [CLASS_FORM_ATTRIBUTES.FREQUENCY]:'once',
  [CLASS_FORM_ATTRIBUTES.CLASS_NAME]:'Farrah',
  [CLASS_FORM_ATTRIBUTES.CREATED_DATE_TIME]:1633489265000,

  [CLASS_FORM_ATTRIBUTES.SELECTED_STUDENT]:[{
  Label: 0,
    value:[
        {
        [STUDENT_ATTRIBUTES.AMOUNT_OF_LESSONS]:1,
         //[key],
        [CLASS_FORM_ATTRIBUTES.STUDENT_STATE]:'quit',
        [STUDENT_ATTRIBUTES.STUDENT_NAME]:'Farrah',
        [STUDENT_ATTRIBUTES.TUITION_VALUE]:'400'
      }
      ]
    }
],
  [CLASS_FORM_ATTRIBUTES.START_DATE_TIME]: '20/12/2021',
  [CLASS_FORM_ATTRIBUTES.STATE]: 'voided'
  }

]

export const testing_finance = [
  {
    [FINANCE_ATTRIBUTES.AMOUNT]: 500,
    [FINANCE_ATTRIBUTES.CATEGORY]: "bank",
    [FINANCE_ATTRIBUTES.DATE]: 1643696340000,
    [FINANCE_ATTRIBUTES.IS_INCOME]: true
  },
  {
    [FINANCE_ATTRIBUTES.AMOUNT]: 212.21,
    [FINANCE_ATTRIBUTES.CATEGORY]: "groupclass",
    [FINANCE_ATTRIBUTES.DATE]: 1643696340000,
    [FINANCE_ATTRIBUTES.IS_INCOME]: true
  },
  {
    [FINANCE_ATTRIBUTES.AMOUNT]: 100.22,
    [FINANCE_ATTRIBUTES.CATEGORY]: "food",
    [FINANCE_ATTRIBUTES.DATE]: 1543696340000,
    [FINANCE_ATTRIBUTES.IS_INCOME]: false
  },
  {
    [FINANCE_ATTRIBUTES.AMOUNT]: 50,
    [FINANCE_ATTRIBUTES.CATEGORY]: "lunch",
    [FINANCE_ATTRIBUTES.DATE]: 1543696340000,
    [FINANCE_ATTRIBUTES.IS_INCOME]: false
  },
  {
    [FINANCE_ATTRIBUTES.AMOUNT]: 56,
    [FINANCE_ATTRIBUTES.CATEGORY]: "lunch",
    [FINANCE_ATTRIBUTES.DATE]: 1543696340000,
    [FINANCE_ATTRIBUTES.IS_INCOME]: false
  },

]

export const testing_location = [
    {[LOCATION_ATTRIBUTES.LABEL]: 'Tai Wai',[LOCATION_ATTRIBUTES.COUNT]:0},
    {[LOCATION_ATTRIBUTES.LABEL]: 'Mui Wo',[LOCATION_ATTRIBUTES.COUNT]:0},
    {[LOCATION_ATTRIBUTES.LABEL]: 'Sai Kung',[LOCATION_ATTRIBUTES.COUNT]:0},
    {[LOCATION_ATTRIBUTES.LABEL]: 'Central',[LOCATION_ATTRIBUTES.COUNT]:0},
    {[LOCATION_ATTRIBUTES.LABEL]: 'Deep Water Bay',[LOCATION_ATTRIBUTES.COUNT]:0}
]
